<h1> Laborator 2</h1>
    <h2>Rezolvarea sistemelor liniare determinate.Sisteme triunghiulare.Eliminarea gaussiană</h2>
    
   Cerinta: Rezolvati sistemul  Ax=b  utilizand eliminarea gausiana cu pivotare partiala(EGPP).  Matricea A are o structura speciala, si prin urmare algoritmul EGPP poate fi imbunatatit. A se consulta suportul de laborator.

In [3]:
import numpy as np
rng = np.random.default_rng(0)  #generator
#----------- Input ---------------------------------
n = 6  # dimensiunea matricei
A = rng.integers(1,11, size = (n,n))
A = np.triu(A,-1)
A[n-1,:] = rng.integers(1,11, size = (1,n))
A =A.astype('float')
b =  rng.integers(-10,11, size = (n,1)).astype('float')
#-------------------------------------------------------------
print('-----------A------------')
print(A)
print('-----------b------------')
print(b)
print("Solution:", np.linalg.inv(A)@b)


#Definiti functia EGPP (Algoritm 2.4)
# [!]: Pentru rezolvarea sistemului Ax = b a se vedea Algoritm 2.6
def linearsolver(A,b):
  n = len(A)
  M = A

  i = 0
  for x in M:
   x = np.append(x, b[i])
   i += 1

  for k in range(n):
   for i in range(k,n):
     if abs(M[i][k]) > abs(M[k][k]):
        M[k], M[i] = M[i],M[k]
     else:
        pass

   for j in range(k+1,n):
       q = float(M[j][k]) / M[k][k]
       for m in range(k, n+1):
          M[j][m] -=  q * M[k][m]

  x = [0 for i in range(n)]

  x[n-1] =float(M[n-1][n])/M[n-1][n-1]
  for i in range (n-1,-1,-1):
    z = 0
    for j in range(i+1,n):
        z = z  + float(M[i][j])*x[j]
    x[i] = float(M[i][n] - z)/M[i][i]
  print(x)

#Algoritmul UTRIS pentru rezolvarea sistemului: Ux = b
def Utris(U,b):
    n = U.shape[0]
    x = np.zeros((n,1))
    for i in range(n-1,-1, -1):
        s = b[i]
        for j in range(i+1,n):
            s =s - U[i][j]*x[j]
        x[i] = s/U[i][i]
    return x


linearsolver(A,b)

-----------A------------
[[ 9.  7.  6.  3.  4.  1.]
 [ 1.  1.  2.  9.  7. 10.]
 [ 0.  7. 10.  8.  7.  6.]
 [ 0.  0.  3.  9.  7.  1.]
 [ 0.  0.  0.  1.  8.  8.]
 [ 1.  3.  5.  5.  5.  1.]]
-----------b------------
[[-10.]
 [ -8.]
 [-10.]
 [  4.]
 [  1.]
 [  3.]]
Solution: [[ 17.77759473]
 [-58.33278418]
 [ 48.60461285]
 [-11.2306425 ]
 [ -7.04448105]
 [  8.57331137]]


NameError: name 'linearsolver' is not defined

In [2]:
print("Smth")

Smth
